# version format
version: 1.1.4.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX will only be used for Release builds
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
install:
  - cmd: set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=
  - cmd: cd BuildPackage
  - cmd: Build.bat

# to disable automatic builds
build: off

artifacts:
  - path: BuildPackage\artifacts\*.nupkg
  - path: BuildPackage\artifacts\*.zip

#deploy:
     # MyGet Deployment for builds & releases
#  - provider: NuGet
#    server: https://www.myget.org/F/packageurl/
#    api_key:
#      secure: 
#    artifact: /.*\.nupkg/
#    on:
#      branch: master

     # GitHub Deployment for releases
#  - provider: GitHub
#    auth_token:
#      secure: 
#    artifact: /.*\.zip/            # upload all Zip packages to release assets
#    draft: false
#    prerelease: false
#    on:
#      branch: master
#      appveyor_repo_tag: true        # deploy on tag push only

     # NuGet Deployment for releases
#  - provider: NuGet
#    server: 
#    api_key:
#      secure: 
#    artifact: /.*\.nupkg/
#    on:
#      branch: master
#      appveyor_repo_tag: true